[package]
name = "rustub"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { version = "2.0.21", default-features = false }
anyhow = { version = "1.0.104", default-features = false, features = ["std"] }
axum = { version = "0.8.9", default-features = false, features = ["http1", "json", "query", "tokio"] }
axum-server = { version = "0.8.0", default-features = false, features = ["tls-rustls"] }
tokio = { version = "1.0", default-features = false, features = ["rt-multi-thread", "macros", "net"] }
serde = { version = "1.0", default-features = false, features = ["derive", "std"] }
serde_json = { version = "1.0", default-features = false, features = ["std"] }
serde_yaml = { version = "0.9.34", default-features = false }
log = { version = "0.4.34", default-features = false, features = ["std"] }
log4rs = { version = "1", default-features = false, features = ["console_appender", "pattern_encoder"] }
walkdir = { version = "2.5.0", default-features = false }
strfmt = { version = "0.2.6", default-features = false }

[dev-dependencies]
quickcheck = { version = "1.0", default-features = false }
